#<<<<<<< HEAD
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://waither-db.cg9dqzfapqgp.ap-northeast-2.rds.amazonaws.com:3306/waither
#=======
#server:
#  port: 80

#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://waither-db.cg9dqzfapqgp.ap-northeast-2.rds.amazonaws.com:3306
#>>>>>>> 995927066e5286e98feac4ae7e25e6b01c5eba43
    username: waither
    password: waither0330

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
#<<<<<<< HEAD
        format_sql: true
#=======
#        format_sql: true


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: d123b0e487f515ba55f26453d6537fbc
            client-secret: yc8CcG3LgvElOJgGY32sXqMyqcR9JNGO
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mail:
    smtp:
      auth: true
      starttls:
        required: true
        enable: true
      socketFactory:
        class: javax.net.ssl.SSLSocketFactory
        fallback: false
        port: 465
      port: 465

  AdminMail:
    id: [ ID ]
    password: [ PW ]




logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

#>>>>>>> 995927066e5286e98feac4ae7e25e6b01c5eba43
