#server:
#  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://waither-db.cg9dqzfapqgp.ap-northeast-2.rds.amazonaws.com:3306
    username: waither
    password: waither0330

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          apple:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/apple
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Apple
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jwk-set-uri: https://appleid.apple.com/auth/keys
  apple:
    APPLE.AUTH.TOKEN.URL: https://appleid.apple.com/auth/token
    APPLE.PUBLICKEY.URL: https://appleid.apple.com/auth/keys
    APPLE.WEBSITE.URL: [ Website URLs ]
    APPLE.ISS: https://appleid.apple.com
    APPLE.AUD: [ Client ID ]
    APPLE.TEAM.ID: [ Team ID ]
    APPLE.KEY.ID: [ Key ID ]

  mail:
    smtp:
      auth: true
      starttls:
        required: true
        enable: true
      socketFactory:
        class: javax.net.ssl.SSLSocketFactory
        fallback: false
        port: 465
      port: 465

  AdminMail:
    id: [ ID ]
    password: [ PW ]




logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

